apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellow
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      ser: web
  template:
    metadata:
      labels:
        ser: web
    spec:
      containers:
        - name: hellow
          image: helloworld
          imagePullPolicy: Never
#          env:
#            - name: PSQL_USERNAME
#              value: postgres
#            - name: PSQL_SOURCE
#              value: qe-portal-rds-aur-cls-dev-ind-ap-south-1.cluster-cvy4bxsmqjig.ap-south-1.rds.amazonaws.com:5432/hs_productivity_metrics
#            - name: PSQL_PASSWORD
#              value: postgres
#            - name: PROFILE
#              value: india

---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: app1
  name: app1
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 30015
  selector:
    ser: web
  type: NodePort
