apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      ser: web
  template:
    metadata:
      labels:
        ser: web
    spec:
      containers:
        - name: myapp
          image: helloworld
          imagePullPolicy: Never
---

apiVersion: v1
kind: Service
type:
metadata:
  labels:
    name: app1
  name: app1
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 30015
  selector:
    ser: web
  type: NodePort
