apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
        - name: endgame-job
          image: 084690408984.dkr.ecr.us-east-1.amazonaws.com/qa-endgame:v251070.3.12
#          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4